In [2]:
import numpy as np

## Creating Numpy Arrays

In [6]:
a=np.array([3,4,5])    #1D A rray
a     

array([3, 4, 5])

In [7]:
np.array([[3,4,5],[6,7,8]])  #2D Array

array([[3, 4, 5],
       [6, 7, 8]])

In [8]:
np.zeros((4,3))  #print rows and columns all zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.arange(0,10,2)
# it is a range start,stop,step gives output in array form

array([0, 2, 4, 6, 8])

In [10]:
np.eye(3)  # print identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
np.ones((3,3))   # print only ones 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [13]:
np.full((3,3),5)  # it means it printd 3 rows and 3 columns of 5

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

## Array Attributes

In [14]:
arr=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
arr

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [15]:
print(arr.shape)  # tells the rows and columns

(1, 3, 3)


In [16]:
print(arr.ndim)  # tells 1D or 2d array

3


In [17]:
print(arr.size)   # total elements

9


In [18]:
print(arr.dtype)   # datatype

int64


In [19]:
print(arr.itemsize)  # bytes per elements

8


## Indexing and Slicing

In [21]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
print(a,[2,4])  # adds the array in 2nd row

[[1 2 3]
 [4 5 6]] [2, 4]


In [40]:
print(a[1,:2])

[4 5]


## Array Operations

In [42]:
a=np.array([4,5,6])
b=np.array([6,7,8])

In [44]:
print(a+b)
print(a*b)
print(a-b)
print(a**b)  # sq roots

[10 12 14]
[24 35 48]
[-2 -2 -2]
[   4096   78125 1679616]


## Broadcasting

In [57]:
a=np.array([[4],[5],[6]])
b=np.array([6,7,8])

In [58]:
print(a.shape)

(3, 1)


In [59]:
print(b.shape)

(3,)


In [60]:
print(a+b)

[[10 11 12]
 [11 12 13]
 [12 13 14]]


## Mathematical Operations

In [3]:
a=np.array([1,2,3,4])

In [4]:
print(a.reshape(2,2))

[[1 2]
 [3 4]]


In [94]:
print(np.mean(a))

2.5


In [95]:
print(np.sum(a))

10


In [96]:
print(np.median(a))

2.5


In [97]:
print(np.var(a))

1.25


In [98]:
print(np.std(a))

1.118033988749895


In [99]:
print(np.max(a))

4


In [100]:
print(np.min(a))

1


In [103]:
print(np.square(a)) 

[ 1  4  9 16]


## Reshaping and Resizing

In [114]:
a=np.array([[1,2],[3,2],[4,5]])
a

array([[1, 2],
       [3, 2],
       [4, 5]])

In [105]:
print(a.reshape(2,3))  # it reshaped into three columns and two rows

[[1 2 3]
 [2 4 5]]


In [106]:
print(a.flatten())  # flattens into 1d array

[1 2 3 2 4 5]


## Random Module in Numpy

In [109]:
a=np.random.seed(0)
a

In [111]:
np.random.rand(3,2)  # gives random float 0 to 1

array([[0.43758721, 0.891773  ],
       [0.96366276, 0.38344152],
       [0.79172504, 0.52889492]])

## Useful functions

In [117]:
s=([1,4,3,5,2])

In [119]:
np.unique(s)

array([1, 2, 3, 4, 5])

In [120]:
np.sort(s)

array([1, 2, 3, 4, 5])

In [121]:
np.argsort(s)

array([0, 4, 2, 1, 3])