In [2]:
import numpy as np

## Creating Numpy Arrays from List

In [3]:
a=np.array([3,4,5])    #1D A rray
a     

array([3, 4, 5])

In [4]:
np.array([[3,4,5],[6,7,8]])  #2D Array

array([[3, 4, 5],
       [6, 7, 8]])

In [6]:
np.array([[[6,7,8],[9,10,11],[12,13,14]]]) ##3d Array

array([[[ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]]])

## Creating Numpy Array From Tuple

In [25]:
a=(1,2,3,4,5)
arr1=np.array(a)
print(arr1)

[1 2 3 4 5]


## Creating Numpy Array From Complex Numbers

In [9]:
a=(1+3j,2-5j,6+9j)
arr2=np.array(a)
print(arr2)

[1.+3.j 2.-5.j 6.+9.j]


In [10]:
a=(1,2)
arr3=np.array(a,dtype=complex)
print(arr3)

[1.+0.j 2.+0.j]


## Creating Arrays with Ones,zeros,Respectively

In [8]:
np.zeros((4,3))  #print rows and columns all zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones((3,3))   # print only ones 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Printing Array with Range of Values

In [12]:
a=np.arange(0,10,2)
print(a) ## it works like range() strat,stop,step

[0 2 4 6 8]


In [15]:
a=np.linspace(0,1,5)
print(a)  ## generate 5 equally spaced numbers between 0 and 5

[0.   0.25 0.5  0.75 1.  ]


## Creating Identity Matrix

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.full((3,3),5) ## it creates array of 3*3 matrix of number 5

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

## Array Attributes

In [26]:
arr=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
arr

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [32]:
print(arr.shape) ## tell the size

(1, 3, 3)


In [31]:
print(arr.dtype) ## teels the data type

int64


In [33]:
print(arr.ndim) ## tells whther 1d,2d,3d array

3


In [34]:
print(arr.size) ## tells the elemnts present in array

9


In [38]:
print(arr.itemsize) ##bytes per elements (arraydtype is 64/8)

8


## Indexing and Slicing

In [ ]:
##Numpy slicing is also like python slicing start part is taken end is not taken

In [26]:
array=np.array([[1,2,3],[4,5,6]])
print(array)

[[1 2 3]
 [4 5 6]]


In [27]:
print(array[1,2])

6


In [28]:
print(array[0,2])  ## prints 0 row and 2nd column

3


In [29]:
print(array[:,2]) ## all rows and column 2

[3 6]


In [30]:
print(array[0,:])  ## all columns and o th row

[1 2 3]


In [35]:
print(array[0:1,1:3]) ## we take oth row and 1 and 2 column 

[[2 3]]


In [36]:
print(array[1:,1:2])

[[5]]


In [34]:
array[0:2, 1:2]

array([[2],
       [5]])

## Array Operations

In [69]:
a=np.array([4,5,6])
b=np.array([6,7,8])

In [75]:
print(a+b)
print(a*b)
print(a-b)
print(a**b) # sq roots
print(np.log(a)) ## natural log
print(np.exp(b)) ## exponential 
print(np.log2(a)) ## base2

[10 12 14]
[24 35 48]
[-2 -2 -2]
[   4096   78125 1679616]
[1.38629436 1.60943791 1.79175947]
[ 403.42879349 1096.63315843 2980.95798704]
[2.         2.32192809 2.5849625 ]
[   4096   78125 1679616]


In [77]:
## comparision
x=np.array([3,4,3])
y=np.array([5,4,5])

result= x==y
print(result)

print(np.all(x<5))

[False  True False]
True


## Broadcasting

In [16]:
a=np.array([[4],[5],[6]])
b=np.array([6,7,8])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
e = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])

In [21]:
print(a)
print(a.shape)  ## 3 rows with 1 column

a+10 ## numpy allows single number to an entire array it expands

[[4]
 [5]
 [6]]
(3, 1)


array([[14],
       [15],
       [16]])

In [20]:
print(b)  ##1 d array with 3 elements
print(b.shape)

print(a+b)

[6 7 8]
(3,)
[[10 11 12]
 [11 12 13]
 [12 13 14]]


In [63]:
print(c.shape) # 2rows with 3 columns

(2, 3)


In [65]:
print(d.shape) # 1 layer with 3 rows and 3 columns

(1, 3, 3)


In [22]:
print(e.shape) ## 2 layers with 3 rows and 3 columns
print(d+e)

(2, 3, 3)
[[[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]

 [[11 13 15]
  [17 19 21]
  [23 25 27]]]


## Axis Concept

In [24]:
a=np.array([[10,20,30],[40,50,60]])
print(a)

[[10 20 30]
 [40 50 60]]


In [29]:
a.sum(axis=0) ## axis 0 means move vertically

array([50, 70, 90])

In [30]:
a.sum(axis=1) ## axis 1 means move horizontally

array([ 60, 150])

In [31]:
a.mean(axis=0) 

array([25., 35., 45.])

In [32]:
a.max(axis=0)

array([40, 50, 60])

In [33]:
a.max(axis=1)

array([30, 60])

In [34]:
a.min(axis=0)

array([10, 20, 30])

## Boolean Indexing

In [38]:
a=np.array([1,2,3,4,5,6])
print(a)
a>3 ## numpy checks every elemnts

[1 2 3 4 5 6]


array([False, False, False,  True,  True,  True])

In [39]:
a[a>3]

array([4, 5, 6])

In [41]:
a[a%2==0]

array([2, 4, 6])

In [44]:
a[(a>2)& (a<5)]

array([3, 4])

## Mathematical Operations

In [107]:
a=np.array([1,2,3,4])

In [108]:
print(a.reshape(2,2))

[[1 2]
 [3 4]]


In [109]:
print(np.mean(a))

2.5


In [110]:
print(np.sum(a))

10


In [111]:
print(np.median(a))

2.5


In [112]:
print(np.var(a))

1.25


In [113]:
print(np.std(a))

1.118033988749895


In [114]:
print(np.max(a))

4


In [115]:
print(np.min(a))

1


In [116]:
print(np.square(a)) 

[ 1  4  9 16]


## Reshaping and Resizing

In [48]:
a=np.array([[1,2],[3,2],[4,5]])
a

array([[1, 2],
       [3, 2],
       [4, 5]])

In [49]:
print(a.reshape(2,3))  # it reshaped into three columns and two rows

[[1 2 3]
 [2 4 5]]


In [50]:
print(a.flatten())  # flattens into 1d array

[1 2 3 2 4 5]


In [51]:
a.ravel()

array([1, 2, 3, 2, 4, 5])

In [54]:
## flatten creates a copy
a=np.array([10,20,30])
b=a.flatten()
b[0]=100
print(a)
print(b)

[10 20 30]
[100  20  30]


In [56]:
## Return the view of the original array
a=np.array([10,20,30])
b=a.ravel()
b[0]=100
print(a)
print(b)

[100  20  30]
[100  20  30]


## Concatenation

In [131]:
Array1=np.array([[1,2,3,4,5],[1,2,3,4,5]])
Array2=np.array([[6,7,8,9,10],[6,7,8,9,10]])

np.concat((Array1,Array2),axis=0) ## means operations performed on rows

array([[ 1,  2,  3,  4,  5],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 6,  7,  8,  9, 10]])

In [132]:
np.concat((Array1,Array2),axis=1) ## performed on columns

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [138]:
np.stack((Array1,Array2),axis=0)

array([[[ 1,  2,  3,  4,  5],
        [ 1,  2,  3,  4,  5]],

       [[ 6,  7,  8,  9, 10],
        [ 6,  7,  8,  9, 10]]])

In [147]:
np.vstack((Array1,Array2)) ## nothing just joins the array horizontially(axis=0)

array([[ 1,  2,  3,  4,  5],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 6,  7,  8,  9, 10]])

In [149]:
np.hstack((Array1,Array2)) ## joins the array vertically (axis=1)columns basically

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

## Random Module in Numpy

In [6]:
np.random.rand(2,3) ## generates an array with random numbers between 0 and 1 of specified size

array([[0.57485552, 0.86972812, 0.68808419],
       [0.6554302 , 0.67925228, 0.14767952]])

In [10]:
np.random.randint(0,11,size=(2,3)) ## generates the number randomly between specified numbers given and size

array([[0, 4, 1],
       [1, 9, 5]], dtype=int32)

## Matrix 

In [46]:
import numpy as np

A = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print("A=",A)

B = np.array([[9, 8, 7],[6, 5, 4],[3, 2, 1]])
print("B=",B)

A= [[1 2 3]
 [4 5 6]
 [7 8 9]]
B= [[9 8 7]
 [6 5 4]
 [3 2 1]]


In [47]:
c=A+B
print(c)  ## operations

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [48]:
c=A*B ## simple multiplication
print(c)

[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [49]:
c=A/B
print(c)

[[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]


In [50]:
c=A%B
print(c)

[[1 2 3]
 [4 0 2]
 [1 0 0]]


In [51]:
c=np.dot(A,B) ## dot product is different multiply each row with each column like 1st row 1 column,1 row 2 column and so on.
print(c)

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [52]:
np.transpose(A) # transpose rows to columns and columns to rows

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [53]:
print(np.linalg.det(A))

0.0


In [56]:
a=np.array([[1,2],[3,4]])
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

## Assignment And copy

In [11]:
a=np.array([1,2,3])
b=a   ## does not create a new array both points to same memory
b[0]=50
print(a)
print(b)

[50  2  3]
[50  2  3]


In [14]:
a=np.array([1,2,3])
b=a.copy() ## here it creates a new array same like a or copy of a
b[1]=50  ## but at index 1 changes the value
print(a)
print(b)

[1 2 3]
[ 1 50  3]


## Useful functions

In [15]:
s=np.array([1,4,3,5,2,2,4,1])

In [16]:
np.unique(s)

array([1, 2, 3, 4, 5])

In [17]:
np.sort(s)

array([1, 1, 2, 2, 3, 4, 4, 5])

In [18]:
np.argsort(s)

array([0, 7, 4, 5, 2, 1, 6, 3])

In [20]:
np.where(s > 5) ## o/p will empty beacuse condition applied is false

(array([], dtype=int64),)

In [37]:
np.clip(s,0,10) ## limits the value of array in limit range if suppose we have a 
                #big array want speific part so we use this

array([1, 4, 3, 5, 2, 2, 4, 1])